version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-local
    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:${VOLUME}

  garage-sim:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: garage-sim
    network_mode: host
    restart: unless-stopped

volumes:
  mysql_data: